# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('job_status', models.CharField(choices=[(0, 'Inactive'), (1, 'Initiated'), (2, 'Processing'), (3, 'Active')], default=0, max_length=1)),
                ('dob', models.DateField()),
                ('cv', models.FileField(upload_to='uploads')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
