# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_recruitment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='dob',
        ),
    ]
