# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-07 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0003_remove_recruitment_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='full_name',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
