# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-07 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20190407_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='job_status',
            field=models.CharField(choices=[(1, 'Inactive'), (2, 'Initiated'), (3, 'Processing'), (4, 'Active')], default=1, max_length=1),
        ),
    ]
